apiVersion: apps/v1
kind: Deployment
metadata:
  name: passenger-service
  namespace: flightbooking-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: passenger-service
  template:
    metadata:
      labels:
        app: passenger-service
    spec:
      containers:
        - name: passenger-service
          image: deadshot007/passenger-service:v0.0.1
          env:
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://configserver-service:8888
          ports:
            - containerPort: 8083

---

apiVersion: v1
kind: Service
metadata:
  name: passenger-service
  namespace: flightbooking-microservices
spec:
  selector:
    app: passenger-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP