apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-service
  namespace: flightbooking-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-service
  template:
    metadata:
      labels:
        app: flight-service
    spec:
      containers:
        - name: flight-service
          image: deadshot007/flight-service:v0.0.2
          env:
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://configserver-service:8888
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: flight-service
  namespace: flightbooking-microservices
spec:
  selector:
    app: flight-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP